version: 1
disable_existing_loggers: False

formatters:
  colorized_with_name:
    "()": colorlog.ColoredFormatter
    format: "%(blue)s[%(asctime)s]%(reset)s %(log_color)s%(levelname)s%(reset)s %(name)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG:    "cyan"
      INFO:     "green"
      WARNING:  "yellow"
      ERROR:    "red"
      CRITICAL: "bold_red"
  
  colorized_without_name:
    "()": colorlog.ColoredFormatter
    format: "%(blue)s[%(asctime)s]%(reset)s %(log_color)s%(levelname)s%(reset)s - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG:    "cyan"
      INFO:     "green"
      WARNING:  "yellow"
      ERROR:    "red"
      CRITICAL: "bold_red"

handlers:
  console_with_name:
    class: logging.StreamHandler
    formatter: colorized_with_name
    stream: ext://sys.stdout
  
  console_without_name:
    class: logging.StreamHandler
    formatter: colorized_without_name
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [console_with_name]

loggers:
  uvicorn:
    level: INFO
    handlers: [console_without_name]
    propagate: no
  watchfiles:
    level: INFO
    handlers: [console_without_name]
    propagate: no
  app:
    level: DEBUG
    handlers: [console_with_name]
    propagate: no




